# This script deploys your website automatically
name: Run and Build

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ main ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Push
        run: git subtree push --prefix dist origin gh-pages
